### ISSUE TITLE
Can't parse backtick and tick for number grouping

### ISSUE THREAD

**Issue by bahrmichael** [E-351/janice#23]
A user whose system language apparently is set to German Swiss German has reported that the parser is not able to handle accent grave and accent acute. Ingame their client shows number grouping with an accent, for example "Jasped 14`000".

Example: https://janice.e-351.com/a/YqwXr6 and https://janice.e-351.com/a/WvNkyZ

Expectation: Same as "Janice 14,000"

**Comment by E-351** [comment]
https://janice.e-351.com/a/u20LSH
https://janice.e-351.com/a/7yVOuP

Should be fixed now.
