### ISSUE TITLE
[Bug] blueprint copies in chinese interface

### ISSUE THREAD

**Issue by undefined-moe** [E-351/janice#29]
When using chinese interface with english keyword name, the copied contract detail for bp copies will be as follows:

```
Harbinger Blueprint*	1	Battlecruiser Blueprint*	Blueprint*	蓝图拷贝 - 流程：1 - 材料效率：10 - 时间效率：20
```

However this will be treated as original bp

**Comment by E-351** [comment]
All blueprints are always treated as originals as in most pastes there isn't enough information to determine whether it's copy or not as well as pricing blueprint copies or researched blueprint originals isn't supported.

**Comment by undefined-moe** [comment]
Understand. But consider adding a warning like "there are blueprints in this appraisal and prices might be incorrect" or try to parse the text "Blueprint Copy", "蓝图拷贝", or in other languages in the extra info section and mark them at zero-price (same as the in-game appraise system)

**Comment by undefined-moe** [comment]
It's really useful for appraising contracts, especially those with lots of junks and some bp copies mixed in it :(
