### ISSUE TITLE
Using Copy function only copies Single item prices no matter what option you have selected. 

### ISSUE THREAD

**Issue by DreadOp** [E-351/janice#39]
As title said, if you use the copy function button it only copies the Single Item price even if you have the Total option selected.

**Comment by E-351** [comment]
This is correct, even though bit unintuitive behavior. You can change what data you want copied by right clicking copy icon in top left corner:

![image](https://github.com/E-351/janice/assets/46429852/5afd0b46-4566-4b55-97e2-2a9a6b48d0ec)
