### ISSUE TITLE
Rounding error when using custom percentage

### ISSUE THREAD

**Issue by matthiasschoger** [E-351/janice#6]
I entered an appraisal with 110% Jita sell.

When I see the resulting appraisal result, the following lines are shown:
"WTB @ 110.00000000000001% Jita sell
This appraisal is valued at 110.00000000000001% of market value."

Just a minor issue, but it looks just wrong.

**Comment by E-351** [comment]
I believe this should be fixed. If not feel free to open new issue specifying where it's still occuring. Thanks
